# Generated by Django 5.0.3 on 2024-03-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuso',
            new_name='Curso',
        ),
    ]
