# Generated by Django 5.0.3 on 2024-03-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_rename_cuso_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('id_comision', models.IntegerField()),
            ],
            options={
                'db_table': 'AppCoder_profesores',
            },
        ),
        migrations.AlterModelTable(
            name='curso',
            table='AppCoder_curso',
        ),
    ]
